### ISSUE TITLE
WaitForEvents type NoDate and AnyDate not working.

### ISSUE THREAD

**Issue by FabioDeBiase** [controlm/automation-api-quickstart#11]
Hello, i'm trying to develop new flows using the automation api on ctm 9.0

What is causing me trouble is that i can't choose for the waitforevents objects with type of NoDate and AnyDate.

When i try to build the flow.json i always get error.
Instead with waitforevents object that use OrderDate or SpecificDate value, the waitforevents is working flawlessy.

Can you check and try why is not working?

Even the example that ctm api web page shows is not working:

"Wait1":
{
          "Type": "WaitForEvents",
          "Events": [
              {"Event":"e1"},
              {"Event":"e2"},
              **{"Event":"e3", "OrderDate":"AnyDate"}** #this line will not work, and will not permit build/deploy, removing this line or changing the value like event e1 and e2 will make the deploy/run work.
          ]
}

**Comment by nathan-amichay** [comment]
It is supported with Automation API version 9.0.5
