### ISSUE TITLE
201-call-restapi-using-curl

### ISSUE THREAD

**Issue by neilcu** [controlm/automation-api-quickstart#13]
The cut for the token is set to f1 in the curl example code. This does not cut the token field in the new version of aapi.
token=$(echo ${login##*token\":\"} | cut -d "\"" -f 1)

When I set the cut to field 8 it resolves the issue.
token=$(echo ${login##*token\":\"} | cut -d "\"" -f 8)

**Comment by MrKoy** [comment]
True. Currently it has the following value:
token=$(echo ${login##*token\":\"} | cut -d "\"" -f 1)

Looks like API response changed and there are some additional spaces now.
It can be fixed also doing it as follows:
token=$(echo ${login##*token\" : \"} | cut -d '"' -f 1)

**Comment by Galgc** [comment]
Thanks for the feedback. Fixed shampoo.

**Comment by ChrisAtBMC** [comment]
Using shell pattern matching and cut extract the token out of a JSON string is somewhat of an anti-pattern. Simple changes in the white-spacing will break this, as seen above. I see this example being used in other repos as well; we should fix this everywhere.

I suggest we change the line to use the right tool for the job, _**jq**_. So, something along the lines of:

`curl -skX POST -H "Content-Type: application/json" -d '{"username": "user", "password":"pass"}' https://endpoint:8443/automation-api/session/login | jq -r '.token'`

**Comment by Galgc** [comment]
I agree that matching spaces is not the right way to go, however I also I think that jq is not the right tool for this as it is not a “standard” tool like shell scripts/awk etc and is not easily available on common Linux distros.

**Comment by ChrisAtBMC** [comment]
jq comes in the standard repositories in Fedora, RHEL, Debian, Ubuntu, OpenSUSE, etc. It's easily available on pretty much every common Linux distro.

Sure we're talking about the same tool? https://stedolan.github.io/jq/download/

It should be considered as "standard" as using cURL.

**Comment by Galgc** [comment]
You are right. I missed that.
I’m reopening and we will update soon (or you can create a pull request with a fix)

**Comment by mchlt** [comment]
@Galgc
Added fix for this issue, see #32
