### ISSUE TITLE
Python code needs updating to Python 3

### ISSUE THREAD

**Issue by adrianyorke** [controlm/automation-api-quickstart#28]
Firstly, thanks for the great repo and sample code.

Python 2 goes End of Life very soon now, 1.1.2020.  Main issue I see is the use of raw_input() built-in function which has been replaced with input() in Python 3 as proposed by PEP 3111:
https://www.python.org/dev/peps/pep-3111/

I believe the majority of users will be using Python 3 now, or at least heading that way very soon so the code is more likely to fail going forward than say 2-3 years ago where Python 2.7 was still very common.  Here's some more details about what has changed in Python 3:
https://docs.python.org/3.0/whatsnew/3.0.html

Another option is that you make the code backwards compatible - here's a simple workaround you can use so input() function resolves in both Python 2 and Python 3:
```python
if hasattr(__builtins__, 'raw_input'):
      input=raw_input
```

I'm happy to create a PR if you would like help with this.

**Comment by codytrey** [comment]
Updated the python script under 201-call-rest-api-using-python in PR #29

**Comment by codytrey** [comment]
@Galgc can you close this issue since the PR was merged?

**Comment by Galgc** [comment]
Fixed. Closing.
