### ISSUE TITLE
Docker image wont build when using workbench VM

### ISSUE THREAD

**Issue by switchboardOp** [controlm/automation-api-quickstart#30]
I tried to follow the tutorial [here](https://docs.bmc.com/docs/automation-api/9019100monthly/tutorial-building-a-docker-container-for-batch-applications-872868710.html) using the workbench appliance running in VirtualBox and the `docker build` step fails with a connection refused being returned by the workbench server.

```
--2019-10-07 18:48:37--  (try: 6)  https://localhost:8443/automation-api/ctm-cli.tgz
Connecting to localhost (localhost)|127.0.0.1|:8443... failed: Connection refused.
Connecting to localhost (localhost)|::1|:8443... failed: Cannot assign requested address.
Retrying.
```

MacOS: 10.14.6 
Docker: 19.03.2 
VirtualBox: 6.0.12 
Workbench Image: 9.0.18.300-20190218.133426-1

**Comment by codytrey** [comment]
what value did you provide for the `CTMHOST` buildarg?

> --build-arg CTMHOST=$CONTROLM_HOST

You should provide the hostname/ip of the machine hosting the workbench VM.

**Comment by switchboardOp** [comment]
I tried with `localhost` and `0.0.0.0` neither worked.
I was running the workbench VM locally.

**Comment by codytrey** [comment]
localhost in this context refers to the temporary docker build container, rather than the host machine. Use the host name or non-loopback ip of the machine hosting both workbench VM

**Comment by switchboardOp** [comment]
Aha, thank you. TIL about networking in the docker build context.
It's working using my Mac's IP.

Why doesn't BMC provide official images?
