### ISSUE TITLE
Unable to create Docker image using the 301-statefulset-agent-to-run-k8s-jobs-using-ai-job/docker

### ISSUE THREAD

**Issue by vrs-learn** [controlm/automation-api-quickstart#63]
## I have been trying to create docker image using the DockerFile in 301-statefulset-agent-to-run-k8s-jobs-using-ai-job/docker repo, but it fails at below step:
-> install agent, setup will be done during statup
                && ctm provision image $AGENT_IMAGE_NAME && echo installation ended successfully \

---------------------------------------------------------------
Below are the logs:
---------------------------------------------------------------
debug:   Locating java command
info:    Located java at:"/bin/java"
info:    downloading https://clm-pun-v1pngr:8443/automation-api/utils/control-m.services.provision-9.20.200.jar into /home/controlm/.ctm/control-m.services.provision-9.20.200.jar
info:    4MB/4MB precent: 100%
debug:   Set proxy settings for java process: http: [undefined]; https: [undefined]; no_proxy: [undefined]
debug:   starting command: "/bin/java"  -jar /home/controlm/.ctm/control-m.services.provision-9.20.200.jar -image "Agent_20.Linux.json" -agent_tag "" -server https://clm-pun-v1pngr:8443/automation-api -action image -environment myenv -ctms "" -name "" -port "" -cert 0 -file ""
info:    Making SSL trust all certificates and all hostnames
info:    OnPrem provision delivery mode
info:    is agent exist cli exception:os json is not one of the supported OS types : Linux, Solaris, AIX, Windows (rc=1)
info:    error while verifying image existence (CtmCliException), os json is not one of the supported OS types : Linux, Solaris, AIX, Windows (rc=1)
error:   failed to verify image existence in server. reason: os json is not one of the supported OS types : Linux, Solaris, AIX, Windows (rc=1)

**Comment by YosiBergman** [comment]
you probably used "ctm provision image (or install) **Agent_20.Linux.json**" - you should use the name without the .json
"ctm provision image Agent_20.Linux"

**Comment by vrs-learn** [comment]
Thank you Yosi, you are right. The build script had the .json name mentioned. I removed it and now I am able to proceed. Thanks for your help
