### ISSUE TITLE
Installation packages

### ISSUE THREAD

**Issue by ggeldenhuis** [controlm/automation-api-quickstart#8]
Hi
It would be super useful to have the API installation and for that matter the client/agent installation for Control-M packaged up into an RPM and DEB file for easier installation on Red Hat and Ubuntu based distros. Having such packages means I can more easily automate configuration of Control-M API and client/agent in tools like Puppet.

**Comment by Galgc** [comment]
Hi, this might be an interesting use case,
As far as I know we already (by now) have an RFE opened on this subject in Control-M
If not - feel free to contact BMC support to open one.
